# Only the ScalaTest tests will be run!
# The scripted tests require Docker which travis does not support
language: scala
scala:
  - 2.10.7
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
