# Only the ScalaTest tests will be run!
# The scripted tests require Docker which travis does not support
language: scala
dist: trusty
scala:
  - 2.10.7
jdk:
  - oraclejdk8
  - openjdk7
services: docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION scripted

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
